-- require "custom.snippets"
--
-- vim.opt.completeopt = { "menu", "menuone", "noselect" }
-- vim.opt.shortmess:append "c"
--
-- local lspkind = require "lspkind"
-- lspkind.init {
--   symbol_map = {
--     Copilot = "",
--   },
-- }
--
-- local kind_formatter = lspkind.cmp_format {
--   mode = "symbol_text",
--   menu = {
--     buffer = "[buf]",
--     nvim_lsp = "[LSP]",
--     nvim_lua = "[api]",
--     path = "[path]",
--     luasnip = "[snip]",
--     gh_issues = "[issues]",
--     tn = "[TabNine]",
--     eruby = "[erb]",
--   },
-- }
--
-- -- Add tailwindcss-colorizer-cmp as a formatting source
-- require("tailwindcss-colorizer-cmp").setup {
--   color_square_width = 2,
-- }
--
-- local cmp = require "cmp"
--
-- cmp.setup {
--   sources = {
--     {
--       name = "lazydev",
--       -- set group index to 0 to skip loading LuaLS completions as lazydev recommends it
--       group_index = 0,
--     },
--     { name = "supermaven" },
--     { name = "nvim_lsp" },
--     { name = "path" },
--     { name = "buffer" },
--   },
--   mapping = {
--     ["<C-n>"] = cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Insert },
--     ["<C-p>"] = cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Insert },
--     ["<C-y>"] = cmp.mapping(
--       cmp.mapping.confirm {
--         behavior = cmp.ConfirmBehavior.Insert,
--         select = true,
--       },
--       { "i", "c" }
--     ),
--   },
--
--   -- Enable luasnip to handle snippet expansion for nvim-cmp
--   snippet = {
--     expand = function(args)
--       vim.snippet.expand(args.body)
--     end,
--   },
--
--   formatting = {
--     fields = { "abbr", "kind", "menu" },
--     expandable_indicator = true,
--     format = function(entry, vim_item)
--       -- Lspkind setup for icons
--       vim_item = kind_formatter(entry, vim_item)
--
--       -- Tailwind colorizer setup
--       vim_item = require("tailwindcss-colorizer-cmp").formatter(entry, vim_item)
--
--       return vim_item
--     end,
--   },
--
--   window = {
--     -- TODO: I don't like this at all for completion window, it takes up way too much space.
--     --  However, I think the docs one could be OK, but I need to fix the highlights for it
--     --
--     -- completion = cmp.config.window.bordered(),
--     -- documentation = cmp.config.window.bordered(),
--   },
-- }
--
-- -- Setup up vim-dadbod
-- cmp.setup.filetype({ "sql" }, {
--   sources = {
--     { name = "vim-dadbod-completion" },
--     { name = "buffer" },
--   },
-- })
